// src/app/layout.tsx
import './globals.css';
import type { Metadata } from 'next';
import { GeistSans } from 'geist/font';
import { I18nextProvider } from 'next-i18next';
import i18nConfig from '../../i18n.config';

export const metadata: Metadata = {
  title: 'KGRG Landing Page',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={GeistSans.variable}>
      <body className="bg-background text-foreground">
        <I18nextProvider i18n={i18nConfig}>
          {children}
        </I18nextProvider>
      </body>
    </html>
  );
}
